// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BlacklistedDomains = __t.object("BlacklistedDomains", {
  id: __t.u64(),
  domain: __t.string(),
});
export type BlacklistedDomains = __Infer<typeof BlacklistedDomains>;

export const EmailVerifications = __t.object("EmailVerifications", {
  id: __t.u64(),
  userId: __t.u64(),
  token: __t.string(),
  expiresAt: __t.u64(),
});
export type EmailVerifications = __Infer<typeof EmailVerifications>;

export const MagicLinks = __t.object("MagicLinks", {
  id: __t.u64(),
  email: __t.string(),
  token: __t.string(),
  expiresAt: __t.u64(),
  used: __t.bool(),
});
export type MagicLinks = __Infer<typeof MagicLinks>;

export const NewsletterSubscribers = __t.object("NewsletterSubscribers", {
  id: __t.u64(),
  email: __t.string(),
  subscribedAt: __t.u64(),
  unsubscribed: __t.bool(),
});
export type NewsletterSubscribers = __Infer<typeof NewsletterSubscribers>;

export const PasswordResets = __t.object("PasswordResets", {
  id: __t.u64(),
  userId: __t.u64(),
  token: __t.string(),
  expiresAt: __t.u64(),
  used: __t.bool(),
});
export type PasswordResets = __Infer<typeof PasswordResets>;

export const Users = __t.object("Users", {
  id: __t.u64(),
  email: __t.string(),
  passwordHash: __t.string(),
  emailVerified: __t.bool(),
  role: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Users = __Infer<typeof Users>;

