import { test, expect } from '@playwright/test';

/**
 * Kanban REST API tests.
 * Tests the /admin/api/kanban/* endpoints directly using Playwright's APIRequestContext.
 * These tests hit the real Turso database.
 */

const BASE = '/admin/api/kanban';
let createdTaskId: string;

test.describe('Kanban API @api', () => {
	test('GET /tasks returns an array', async ({ request }) => {
		const res = await request.get(`${BASE}/tasks`);
		expect(res.status()).toBe(200);

		const body = await res.json();
		expect(Array.isArray(body)).toBe(true);
	});

	test('POST /tasks creates a task and returns id', async ({ request }) => {
		const res = await request.post(`${BASE}/tasks`, {
			data: {
				title: '[test] Playwright-created task',
				description: 'Auto-generated by Playwright test suite',
				expected_outcome: 'Task exists in DB then gets deleted',
				status: 'backlog',
				assignee: 'playwright',
				workstream: 'QA / Testing'
			}
		});

		expect(res.status()).toBe(201);
		const body = await res.json();
		expect(body).toHaveProperty('id');
		expect(typeof body.id).toBe('string');

		// Save for subsequent tests in this describe block
		createdTaskId = body.id;
	});

	test('GET /tasks contains the newly created task', async ({ request }) => {
		// Depends on createdTaskId being set by previous test
		test.skip(!createdTaskId, 'Creation test did not run — skipping');

		const res = await request.get(`${BASE}/tasks`);
		const tasks = await res.json();
		const found = tasks.find((t: { id: string }) => t.id === createdTaskId);
		expect(found).toBeDefined();
		expect(found.title).toBe('[test] Playwright-created task');
	});

	test('PATCH /tasks/:id updates the task status', async ({ request }) => {
		test.skip(!createdTaskId, 'Creation test did not run — skipping');

		const res = await request.patch(`${BASE}/tasks/${createdTaskId}`, {
			data: { status: 'done' }
		});
		expect(res.status()).toBe(200);
	});

	test('POST /tasks/:id/comments adds a comment', async ({ request }) => {
		test.skip(!createdTaskId, 'Creation test did not run — skipping');

		const res = await request.post(`${BASE}/tasks/${createdTaskId}/comments`, {
			data: {
				author: 'playwright',
				body: 'Auto-generated test comment'
			}
		});
		expect(res.status()).toBe(201);
	});

	test('GET /focus returns focus data', async ({ request }) => {
		const res = await request.get(`${BASE}/focus`);
		expect(res.status()).toBe(200);
		const body = await res.json();
		// Response shape: { focus: string }
		expect(body).toHaveProperty('focus');
		expect(typeof body.focus).toBe('string');
	});

	test('DELETE /tasks/:id removes the task', async ({ request }) => {
		test.skip(!createdTaskId, 'Creation test did not run — skipping');

		const res = await request.delete(`${BASE}/tasks/${createdTaskId}`);
		expect(res.status()).toBe(200);

		// Verify it's gone
		const listRes = await request.get(`${BASE}/tasks`);
		const tasks = await listRes.json();
		const found = tasks.find((t: { id: string }) => t.id === createdTaskId);
		expect(found).toBeUndefined();
	});
});
