// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBlacklistedDomainReducer from "../add_blacklisted_domain_reducer";
import ConsumeMagicLinkReducer from "../consume_magic_link_reducer";
import CreateMagicLinkReducer from "../create_magic_link_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RequestPasswordResetReducer from "../request_password_reset_reducer";
import ResetPasswordReducer from "../reset_password_reducer";
import SeedBlacklistedDomainsReducer from "../seed_blacklisted_domains_reducer";
import SubscribeNewsletterReducer from "../subscribe_newsletter_reducer";
import UnsubscribeNewsletterReducer from "../unsubscribe_newsletter_reducer";
import VerifyEmailReducer from "../verify_email_reducer";

export type AddBlacklistedDomainParams = __Infer<typeof AddBlacklistedDomainReducer>;
export type ConsumeMagicLinkParams = __Infer<typeof ConsumeMagicLinkReducer>;
export type CreateMagicLinkParams = __Infer<typeof CreateMagicLinkReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RequestPasswordResetParams = __Infer<typeof RequestPasswordResetReducer>;
export type ResetPasswordParams = __Infer<typeof ResetPasswordReducer>;
export type SeedBlacklistedDomainsParams = __Infer<typeof SeedBlacklistedDomainsReducer>;
export type SubscribeNewsletterParams = __Infer<typeof SubscribeNewsletterReducer>;
export type UnsubscribeNewsletterParams = __Infer<typeof UnsubscribeNewsletterReducer>;
export type VerifyEmailParams = __Infer<typeof VerifyEmailReducer>;

